### ISSUE TITLE
Initial thumbnail size of selected images

### ISSUE THREAD

**Issue by dameer** [schrapel/carbon-fields-image-gallery#1]
I wasn't able to create branch out of master (any restrictions? sorry, I'm not a git geek) so I'll have to do it this way...

"js/field.js", line #165 says:
`selection.url`
...but I guess it should be:
`selection.sizes.thumbnail.url`

That should fix initial image size upon insertion. Otherwise you gonna end up with a bad preview - unless metabox saved. Hope it helps!

Great work, Image Gallery field should be a part of Carbon Fields!

**Comment by schrapel** [comment]
Thanks for letting me know about this @dameer 

What you need to do is create a fork of this repo, make your change, push to your fork and then do a pull request on this repository. The article is old but worth reading https://yangsu.github.io/pull-request-tutorial/

If you can't figure it out I'll make the change in a few days but I'd prefer to attribute the commit to you

**Comment by dameer** [comment]
I already contributed a bit to Kirki so I'm not a total rookie :) But for some reason I'm not allowed to do Pull Request. Not sure what's wrong with my account (I'm signed in), this is what I get each and every time I try to send request
![login_failed](https://cloud.githubusercontent.com/assets/1826261/24092829/1badd27c-0d51-11e7-9b00-996d90314683.png)
So, no hard feelings from my end if you just attribute the commit to yourself. I'll be glad if it helps, that's the sense making point :)

**Comment by schrapel** [comment]
Like I said you need to create a fork. Click the button in the top right hand corner of this page. Make the change on your version. Then submit a pull request from your version to mine

**Comment by dameer** [comment]
I know mate, I created a fork, the problem is authentication failure that pops up each time I try to Pull Request. And my GitHub app Preferences are just fine. Tried to delete auth key from Keychain Access and sign back in but it doesn't make the difference.
I guess it's up to my Mac's permissions but don't have time to play with it right now.

**Comment by schrapel** [comment]
You do not have a fork otherwise it would show up

https://github.com/dameer/carbon-fields-image-gallery/

**Comment by dameer** [comment]
Thanks for a hint man, it looks like I was pulling request to your own account all the time. Didn't use GitHub for over a year, shame on me.
Best regards!!!

**Comment by schrapel** [comment]
Resolved by #2
